### PR TITLE
Fix #464 v4, story table row matches on wrong trigger var when there's

### LINKED ISSUE #464: Bug: Story table doesn't use trigger variable when it should
kiln v3.0.3 <- we need to put these version numbers in reports

I was running tests for AssemblyLine recently and noticed some were passing that should be failing (the exhibits tests). A row was being used for two pages when it should have just been used for one.

```
    | var | value | trigger |
    | x.has_exhibits | True | exhibit_doc_defaults_1.exhibits.has_exhibits |
```

The `exhibit_doc_defaults_1.exhibits.has_exhibits` trigger variable wasn't preventing this row from setting its value for a page with a different trigger variable.

Debugging logs showed this:

First page, which was handled correctly: page trigger `"trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"`, matches:
```js
[{"original":{"var":"x.has_exhibits","value":"True","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},"var":"x.has_exhibits","value":"True","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits","times_used":0}]
```

On the second loop, the match is clearly incorrect: page trigger `"trigger":"exhibit_doc_custom_1.exhibits.has_exhibits"`, matches:
```js
[{"original":{"var":"x.has_exhibits","value":"True","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},"var":"x.has_exhibits","value":"True","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits","times_used":1}]
```

You can see the trigger variables in that second loop don't match each other. Haven't yet looked into why that would be, but this test is passing incorrectly.

Full test:
```
@alexhibits @e2
Scenario: User adds only a docx exhibit
  And the max seconds for each step is 200
  Given I start the interview at "test_alexhibit"
  And I get to "end alexhibit tests" with this data:
    | var | value | trigger |
    | x.has_exhibits | True | exhibit_doc_defaults_1.exhibits.has_exhibits |
    | x[0].title | DOCX only | exhibit_doc_defaults_1.exhibits.has_exhibits |
    | x[0].pages | test_alexhibit_docx_1.docx | exhibit_doc_defaults_1.exhibits.has_exhibits |
    | x[i].pages.target_number | 1 | exhibit_doc_defaults_1.exhibits[0].pages.there_is_another |
    | x.target_number | 1 | exhibit_doc_defaults_1.exhibits.there_is_another |
```

Full debug:
```Trace: Getting project name
User adds only a docx exhibit
Report:
 type: heading, value: 
---------------
Scenario: User adds only a docx exhibit aldocument alexhibits e 
---------------
..Trace: Getting project name
.scope.normalizedTable():
 [{"original":{"var":"x.has_exhibits","value":"True","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},"var":"x.has_exhibits","value":"True","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits","times_used":0},{"original":{"var":"x[0].title","value":"DOCX only","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},"var":"x[0].title","value":"DOCX only","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits","times_used":0},{"original":{"var":"x[0].pages","value":"test_alexhibit_docx_1.docx","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},"var":"x[0].pages","value":"test_alexhibit_docx_1.docx","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits","times_used":0},{"original":{"var":"x[i].pages.target_number","value":"1","trigger":"exhibit_doc_defaults_1.exhibits[0].pages.there_is_another"},"var":"x[i].pages.target_number","value":"1","trigger":"exhibit_doc_defaults_1.exhibits[0].pages.there_is_another","times_used":0},{"original":{"var":"x.target_number","value":"1","trigger":"exhibit_doc_defaults_1.exhibits.there_is_another"},"var":"x.target_number","value":"1","trigger":"exhibit_doc_defaults_1.exhibits.there_is_another","times_used":0}]
~~~~~~~~~~~~~~ scope.setFields() ~~~~~~~~~~~~~~
Report:
 type: page_id, value: any-exhibits
page fields:
[{"selector":"#daquestion input[name=\"eC5oYXNfZXhoaWJpdHM\"][value=\"True\"][id=\"eC5oYXNfZXhoaWJpdHM_0\"][class=\"da-to-labelauty labelauty da-active-invisible dafullwidth\"]","tag":"input","guesses":[{"var":"x.has_exhibits","value":"True"}],"type":"radio","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},{"selector":"#daquestion input[name=\"eC5oYXNfZXhoaWJpdHM\"][value=\"False\"][id=\"eC5oYXNfZXhoaWJpdHM_1\"][class=\"da-to-labelauty labelauty da-active-invisible dafullwidth\"]","tag":"input","guesses":[{"var":"x.has_exhibits","value":"False"}],"type":"radio","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},{"selector":"#daquestion input[name=\"X2ZpZWxkXzI\"][id=\"X2ZpZWxkXzI\"][class=\"form-control\"]","tag":"input","guesses":[{"var":"x[0].title","value":""}],"type":"text","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},{"selector":"#daquestion input[id=\"fileinput-X2ZpZWxkXzM\"][class=\"file-caption-name\"]","tag":"input","guesses":[],"type":"","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},{"selector":"#daquestion input[name=\"X2ZpZWxkXzM\"][id=\"X2ZpZWxkXzM\"][class=\"dafile\"]","tag":"input","guesses":[{"var":"x[0].pages","value":""}],"type":"file","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},{"selector":"#daquestion button[class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[],"type":"submit","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"}]
matches:
 [{"original":{"var":"x.has_exhibits","value":"True","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},"var":"x.has_exhibits","value":"True","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits","times_used":0}]
Report:
 type: row, value:       | x.has_exhibits | True | exhibit_doc_defaults_1.exhibits.has_exhibits |
*matches:
 []
matches:
 [{"original":{"var":"x[0].title","value":"DOCX only","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},"var":"x[0].title","value":"DOCX only","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits","times_used":0}]
Report:
 type: row, value:       | x[0].title | DOCX only | exhibit_doc_defaults_1.exhibits.has_exhibits |
*matches:
 []
matches:
 [{"original":{"var":"x[0].pages","value":"test_alexhibit_docx_1.docx","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},"var":"x[0].pages","value":"test_alexhibit_docx_1.docx","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits","times_used":0}]
Report:
 type: row, value:       | x[0].pages | test_alexhibit_docx_1.docx | exhibit_doc_defaults_1.exhibits.has_exhibits |
*matches:
 []
matches:
 []
matches:
 []
>~~~~~~~~~~~~~~ scope.setFields() ~~~~~~~~~~~~~~
Report:
 type: page_id, value: exhibit-i-has-additional-pages
page fields:
[{"selector":"#daquestion button[class=\"btn btn-link btn-da daquestionbackbutton danonsubmit\"]","tag":"button","guesses":[],"type":"button","trigger":"exhibit_doc_defaults_1.exhibits[0].pages.there_is_another"},{"selector":"#daquestion button[name=\"eFtpXS5wYWdlcy50aGVyZV9pc19hbm90aGVy\"][value=\"False\"][class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[{"var":"x[i].pages.there_is_another","value":"False"}],"type":"submit","trigger":"exhibit_doc_defaults_1.exhibits[0].pages.there_is_another"},{"selector":"#daquestion button[name=\"eFtpXS5wYWdlcy50aGVyZV9pc19hbm90aGVy\"][value=\"True\"][class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[{"var":"x[i].pages.there_is_another","value":"True"}],"type":"submit","trigger":"exhibit_doc_defaults_1.exhibits[0].pages.there_is_another"}]
matches:
 []
matches:
 [{"artificial":true,"source":{"original":{"var":"x[i].pages.target_number","value":"1","trigger":"exhibit_doc_defaults_1.exhibits[0].pages.there_is_another"},"var":"x[i].pages.target_number","value":"1","trigger":"exhibit_doc_defaults_1.exhibits[0].pages.there_is_another","times_used":0},"var":"x[i].pages.there_is_another","value":"False","trigger":"exhibit_doc_defaults_1.exhibits[0].pages.there_is_another"}]
Report:
 type: row, value:       | x[i].pages.target_number | 1 | exhibit_doc_defaults_1.exhibits[0].pages.there_is_another |
v~~~~~~~~~~~~~~ scope.setFields() ~~~~~~~~~~~~~~
Report:
 type: page_id, value: another-exhibit
page fields:
[{"selector":"#daquestion button[class=\"btn btn-link btn-da daquestionbackbutton danonsubmit\"]","tag":"button","guesses":[],"type":"button","trigger":"exhibit_doc_defaults_1.exhibits.there_is_another"},{"selector":"#daquestion button[name=\"eC50aGVyZV9pc19hbm90aGVy\"][value=\"False\"][class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[{"var":"x.there_is_another","value":"False"}],"type":"submit","trigger":"exhibit_doc_defaults_1.exhibits.there_is_another"},{"selector":"#daquestion button[name=\"eC50aGVyZV9pc19hbm90aGVy\"][value=\"True\"][class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[{"var":"x.there_is_another","value":"True"}],"type":"submit","trigger":"exhibit_doc_defaults_1.exhibits.there_is_another"}]
matches:
 []
matches:
 [{"artificial":true,"source":{"original":{"var":"x.target_number","value":"1","trigger":"exhibit_doc_defaults_1.exhibits.there_is_another"},"var":"x.target_number","value":"1","trigger":"exhibit_doc_defaults_1.exhibits.there_is_another","times_used":0},"var":"x.there_is_another","value":"False","trigger":"exhibit_doc_defaults_1.exhibits.there_is_another"}]
Report:
 type: row, value:       | x.target_number | 1 | exhibit_doc_defaults_1.exhibits.there_is_another |
v~~~~~~~~~~~~~~ scope.setFields() ~~~~~~~~~~~~~~
Report:
 type: page_id, value: any-exhibits
page fields:
[{"selector":"#daquestion input[name=\"eC5oYXNfZXhoaWJpdHM\"][value=\"True\"][id=\"eC5oYXNfZXhoaWJpdHM_0\"][class=\"da-to-labelauty labelauty da-active-invisible dafullwidth\"]","tag":"input","guesses":[{"var":"x.has_exhibits","value":"True"}],"type":"radio","trigger":"exhibit_doc_custom_1.exhibits.has_exhibits"},{"selector":"#daquestion input[name=\"eC5oYXNfZXhoaWJpdHM\"][value=\"False\"][id=\"eC5oYXNfZXhoaWJpdHM_1\"][class=\"da-to-labelauty labelauty da-active-invisible dafullwidth\"]","tag":"input","guesses":[{"var":"x.has_exhibits","value":"False"}],"type":"radio","trigger":"exhibit_doc_custom_1.exhibits.has_exhibits"},{"selector":"#daquestion input[name=\"X2ZpZWxkXzI\"][id=\"X2ZpZWxkXzI\"][class=\"form-control\"]","tag":"input","guesses":[{"var":"x[0].title","value":""}],"type":"text","trigger":"exhibit_doc_custom_1.exhibits.has_exhibits"},{"selector":"#daquestion input[id=\"fileinput-X2ZpZWxkXzM\"][class=\"file-caption-name\"]","tag":"input","guesses":[],"type":"","trigger":"exhibit_doc_custom_1.exhibits.has_exhibits"},{"selector":"#daquestion input[name=\"X2ZpZWxkXzM\"][id=\"X2ZpZWxkXzM\"][class=\"dafile\"]","tag":"input","guesses":[{"var":"x[0].pages","value":""}],"type":"file","trigger":"exhibit_doc_custom_1.exhibits.has_exhibits"},{"selector":"#daquestion button[class=\"btn btn-link btn-da daquestionbackbutton danonsubmit\"]","tag":"button","guesses":[],"type":"button","trigger":"exhibit_doc_custom_1.exhibits.has_exhibits"},{"selector":"#daquestion button[class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[],"type":"submit","trigger":"exhibit_doc_custom_1.exhibits.has_exhibits"}]
matches:
 [{"original":{"var":"x.has_exhibits","value":"True","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},"var":"x.has_exhibits","value":"True","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits","times_used":1}]
Report:
 type: row, value:       | x.has_exhibits | True | exhibit_doc_defaults_1.exhibits.has_exhibits |
*matches:
 []
matches:
 [{"original":{"var":"x[0].title","value":"DOCX only","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},"var":"x[0].title","value":"DOCX only","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits","times_used":1}]
Report:
 type: row, value:       | x[0].title | DOCX only | exhibit_doc_defaults_1.exhibits.has_exhibits |
*matches:
 []
matches:
 [{"original":{"var":"x[0].pages","value":"test_alexhibit_docx_1.docx","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits"},"var":"x[0].pages","value":"test_alexhibit_docx_1.docx","trigger":"exhibit_doc_defaults_1.exhibits.has_exhibits","times_used":1}]
Report:
 type: row, value:       | x[0].pages | test_alexhibit_docx_1.docx | exhibit_doc_defaults_1.exhibits.has_exhibits |
*matches:
 []
matches:
 []
matches:
 []
matches:
 []
matches:
 []
>~~~~~~~~~~~~~~ scope.setFields() ~~~~~~~~~~~~~~
Report:
 type: page_id, value: exhibit-i-has-additional-pages
page fields:
[{"selector":"#daquestion button[class=\"btn btn-link btn-da daquestionbackbutton danonsubmit\"]","tag":"button","guesses":[],"type":"button","trigger":"exhibit_doc_custom_1.exhibits[0].pages.there_is_another"},{"selector":"#daquestion button[name=\"eFtpXS5wYWdlcy50aGVyZV9pc19hbm90aGVy\"][value=\"False\"][class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[{"var":"x[i].pages.there_is_another","value":"False"}],"type":"submit","trigger":"exhibit_doc_custom_1.exhibits[0].pages.there_is_another"},{"selector":"#daquestion button[name=\"eFtpXS5wYWdlcy50aGVyZV9pc19hbm90aGVy\"][value=\"True\"][class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[{"var":"x[i].pages.there_is_another","value":"True"}],"type":"submit","trigger":"exhibit_doc_custom_1.exhibits[0].pages.there_is_another"}]
matches:
 []
matches:
 [{"artificial":true,"source":{"original":{"var":"x[i].pages.target_number","value":"1","trigger":"exhibit_doc_defaults_1.exhibits[0].pages.there_is_another"},"var":"x[i].pages.target_number","value":"1","trigger":"exhibit_doc_defaults_1.exhibits[0].pages.there_is_another","times_used":1},"var":"x[i].pages.there_is_another","value":"False","trigger":"exhibit_doc_defaults_1.exhibits[0].pages.there_is_another"}]
Report:
 type: row, value:       | x[i].pages.target_number | 1 | exhibit_doc_defaults_1.exhibits[0].pages.there_is_another |
v~~~~~~~~~~~~~~ scope.setFields() ~~~~~~~~~~~~~~
Report:
 type: page_id, value: another-exhibit
page fields:
[{"selector":"#daquestion button[class=\"btn btn-link btn-da daquestionbackbutton danonsubmit\"]","tag":"button","guesses":[],"type":"button","trigger":"exhibit_doc_custom_1.exhibits.there_is_another"},{"selector":"#daquestion button[name=\"eC50aGVyZV9pc19hbm90aGVy\"][value=\"False\"][class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[{"var":"x.there_is_another","value":"False"}],"type":"submit","trigger":"exhibit_doc_custom_1.exhibits.there_is_another"},{"selector":"#daquestion button[name=\"eC50aGVyZV9pc19hbm90aGVy\"][value=\"True\"][class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[{"var":"x.there_is_another","value":"True"}],"type":"submit","trigger":"exhibit_doc_custom_1.exhibits.there_is_another"}]
matches:
 []
matches:
 [{"artificial":true,"source":{"original":{"var":"x.target_number","value":"1","trigger":"exhibit_doc_defaults_1.exhibits.there_is_another"},"var":"x.target_number","value":"1","trigger":"exhibit_doc_defaults_1.exhibits.there_is_another","times_used":1},"var":"x.there_is_another","value":"False","trigger":"exhibit_doc_defaults_1.exhibits.there_is_another"}]
Report:
 type: row, value:       | x.target_number | 1 | exhibit_doc_defaults_1.exhibits.there_is_another |
v~~~~~~~~~~~~~~ scope.setFields() ~~~~~~~~~~~~~~
Report:
 type: page_id, value: thumbnails-defaults
page fields:
[{"selector":"#daquestion button[class=\"btn btn-link btn-da daquestionbackbutton danonsubmit\"]","tag":"button","guesses":[],"type":"button","trigger":"thumbnails_defaults"},{"selector":"#daquestion button[name=\"dGh1bWJuYWlsc19kZWZhdWx0cw\"][value=\"True\"][class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[{"var":"thumbnails_defaults","value":"True"}],"type":"submit","trigger":"thumbnails_defaults"}]
matches:
 []
matches:
 []
>~~~~~~~~~~~~~~ scope.setFields() ~~~~~~~~~~~~~~
Report:
 type: page_id, value: download-list-defaults
page fields:
[{"selector":"#daquestion button[class=\"btn btn-link btn-da daquestionbackbutton danonsubmit\"]","tag":"button","guesses":[],"type":"button","trigger":"download_list_defaults"},{"selector":"#daquestion button[name=\"ZG93bmxvYWRfbGlzdF9kZWZhdWx0cw\"][value=\"True\"][class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[{"var":"download_list_defaults","value":"True"}],"type":"submit","trigger":"download_list_defaults"}]
matches:
 []
matches:
 []
>~~~~~~~~~~~~~~ scope.setFields() ~~~~~~~~~~~~~~
Report:
 type: page_id, value: thumbnails-custom
page fields:
[{"selector":"#daquestion button[class=\"btn btn-link btn-da daquestionbackbutton danonsubmit\"]","tag":"button","guesses":[],"type":"button","trigger":"thumbnails_custom"},{"selector":"#daquestion button[name=\"dGh1bWJuYWlsc19jdXN0b20\"][value=\"True\"][class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[{"var":"thumbnails_custom","value":"True"}],"type":"submit","trigger":"thumbnails_custom"}]
matches:
 []
matches:
 []
>~~~~~~~~~~~~~~ scope.setFields() ~~~~~~~~~~~~~~
Report:
 type: page_id, value: download-list-html-custom-1
page fields:
[{"selector":"#daquestion button[class=\"btn btn-link btn-da daquestionbackbutton danonsubmit\"]","tag":"button","guesses":[],"type":"button","trigger":"download_list_html_custom_1"},{"selector":"#daquestion button[name=\"ZG93bmxvYWRfbGlzdF9odG1sX2N1c3RvbV8x\"][value=\"True\"][class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[{"var":"download_list_html_custom_1","value":"True"}],"type":"submit","trigger":"download_list_html_custom_1"}]
matches:
 []
matches:
 []
>~~~~~~~~~~~~~~ scope.setFields() ~~~~~~~~~~~~~~
Report:
 type: page_id, value: download-list-html-custom-2
page fields:
[{"selector":"#daquestion button[class=\"btn btn-link btn-da daquestionbackbutton danonsubmit\"]","tag":"button","guesses":[],"type":"button","trigger":"download_list_html_custom_2"},{"selector":"#daquestion button[name=\"ZG93bmxvYWRfbGlzdF9odG1sX2N1c3RvbV8y\"][value=\"True\"][class=\"btn btn-da btn-primary\"]","tag":"button","guesses":[{"var":"download_list_html_custom_2","value":"True"}],"type":"submit","trigger":"download_list_html_custom_2"}]
matches:
 []
matches:
 []
>Report:
 type: note, value: 
  Rows that got set:
Report:
 type: step, value:     And I get the question id "end alexhibit tests" with this data:
Report:
 type: row, value:       | var | value | trigger |
Report:
 type: row, value:       | x.has_exhibits | True | exhibit_doc_defaults_1.exhibits.has_exhibits |
Report:
 type: row, value:       | x.target_number | 1 | exhibit_doc_defaults_1.exhibits.there_is_another |
Report:
 type: row, value:       | x[0].pages | test_alexhibit_docx_1.docx | exhibit_doc_defaults_1.exhibits.has_exhibits |
Report:
 type: row, value:       | x[0].title | DOCX only | exhibit_doc_defaults_1.exhibits.has_exhibits |
Report:
 type: row, value:       | x[i].pages.target_number | 1 | exhibit_doc_defaults_1.exhibits[0].pages.there_is_another |
Report:
 type: note, value:   All rows were used
Report:
 type: note, value: 
..

Assembly Line Kiln Automated Testing Report - Fri, 31 Dec 2021 20:26:47 GMT


===============================
===============================
Passed scenarios:

---------------
Scenario: User adds only a docx exhibit aldocument alexhibits e 
---------------
screen id: any-exhibits
      | x.has_exhibits | True | exhibit_doc_defaults_1.exhibits.has_exhibits |
      | x[0].title | DOCX only | exhibit_doc_defaults_1.exhibits.has_exhibits |
      | x[0].pages | test_alexhibit_docx_1.docx | exhibit_doc_defaults_1.exhibits.has_exhibits |
screen id: exhibit-i-has-additional-pages
      | x[i].pages.target_number | 1 | exhibit_doc_defaults_1.exhibits[0].pages.there_is_another |
screen id: another-exhibit
      | x.target_number | 1 | exhibit_doc_defaults_1.exhibits.there_is_another |
screen id: any-exhibits
      | x.has_exhibits | True | exhibit_doc_defaults_1.exhibits.has_exhibits |
      | x[0].title | DOCX only | exhibit_doc_defaults_1.exhibits.has_exhibits |
      | x[0].pages | test_alexhibit_docx_1.docx | exhibit_doc_defaults_1.exhibits.has_exhibits |
screen id: exhibit-i-has-additional-pages
      | x[i].pages.target_number | 1 | exhibit_doc_defaults_1.exhibits[0].pages.there_is_another |
screen id: another-exhibit
      | x.target_number | 1 | exhibit_doc_defaults_1.exhibits.there_is_another |
screen id: thumbnails-defaults
screen id: download-list-defaults
screen id: thumbnails-custom
screen id: download-list-html-custom-1
screen id: download-list-html-custom-2

  Rows that got set:
    And I get the question id "end alexhibit tests" with this data:
      | var | value | trigger |
      | x.has_exhibits | True | exhibit_doc_defaults_1.exhibits.has_exhibits |
      | x.target_number | 1 | exhibit_doc_defaults_1.exhibits.there_is_another |
      | x[0].pages | test_alexhibit_docx_1.docx | exhibit_doc_defaults_1.exhibits.has_exhibits |
      | x[0].title | DOCX only | exhibit_doc_defaults_1.exhibits.has_exhibits |
      | x[i].pages.target_number | 1 | exhibit_doc_defaults_1.exhibits[0].pages.there_is_another |
  All rows were used
```

### PR DESCRIPTION
**Pull request by plocket**
[Just like #467, but for v4 branch. I'm not sure I'm loving this workflow, but hopefully we'll be able to drop v3 soon.]

only one row for the relevant variable. Closes #464.

E.g. When, in the story table, there should be
```
    | x[i].name.first | Sam | proxy_list[0].name.first |
    | x[i].name.first | Pat | proxy_list[1].name.first |
```

there's only
```
    | x[i].name.first | Sam | proxy_list[0].name.first |
```

the test shouldn't match on the page that's setting `proxy_list[1].name.first`, but it does, and it fills in "Sam" for the value.

Also
- enhance reports about the problem.
- avoids trigger var check entirely when it's not from a story table.

Edit:
Made some report strings more friendly, but they only get triggered in our unit tests
(which are faster and more focused than our integrated tests) and our unit tests don't
log or save their reports, so I'm providing sample output here of the three fancy reports:

```
Do you have a duplicate story table row? Multiple story table rows match this field's variable name. The test will use the last row that matched. See https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing/#trigger.
The matching rows:
      | text_input | Some one-line text |  |
      | text_input | Some conflicting text |  |
This field's data:
{"selector":"#daquestion input[name=\"dGV4dF9pbnB1dA\"][id=\"dGV4dF9pbnB1dA\"][class=\"form-control\"]","tag":"input","guesses":[{"var":"text_input","value":""}],"type":"text","trigger":"direct_standard_fields"}
```
```
Is this story table missing a row? 1 story table row(s) matched a field name, but none of their trigger variable name(s) matched the trigger variable name in the screen's HTML. The test will have to ignore this field. See https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing/#trigger.
The data of row(s) with conflicting trigger name(s):
      | x[i].name.first | Firstname | proxy_list[0].name.first |
This field's data:
{"selector":"#daquestion input[name=\"eFtpXS5uYW1lLmZpcnN0\"][id=\"eFtpXS5uYW1lLmZpcnN0\"][class=\"form-control\"]","tag":"input","guesses":[{"var":"x[i].name.first","value":""}],"type":"text","trigger":"proxy_list[1].name.first"}
```
```
This story table row needs a value in the "trigger" column, but it is empty. The test might get unexpected results. See https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing/#trigger.
The row's data:
      | x[i].name.first | Firstname |  |
This field's data:
{"selector":"#daquestion input[name=\"eFtpXS5uYW1lLmZpcnN0\"][id=\"eFtpXS5uYW1lLmZpcnN0\"][class=\"form-control\"]","tag":"input","guesses":[{"var":"x[i].name.first","value":""}],"type":"text","trigger":"proxy_list[1].name.first"}
```

### CODE REVIEW

File: lib/scope.js [hunk 1]
```diff
@@ -826,36 +838,73 @@ module.exports = {
     // data for `users[0]`, there's no need to check the trigger var.
     // That way devs with simple cases can ignore the trigger var column.
 
-    // If field uses proxies and there has been more than one match
-    // we now use the trigger var to narrow down the matches.
-    if ( uses_proxies && matches.length > 1 ) {
```
Comment (plocket) [inline lib/scope.js:831]: This was the line that was causing the problem, but fixing it meant I had to change other things so they wouldn't break.

File: lib/scope.js [hunk 2]
```diff
@@ -878,18 +885,23 @@ module.exports = {
 
         if ( row_matches ) {
           matches.push( var_datum );  // Collect all matches to start with.
+          // If the field uses proxy variables - x, i, j, etc, flag it. See more notes below.
```
Comment (rpigneri-vol) [inline lib/scope.js:888]: We have decided to move this to above 892.

File: lib/scope.js [hunk 3]
```diff
@@ -909,36 +921,73 @@ module.exports = {
...
-      // Multiple matches means this came from a story
-
-      // Feedback for devs - we need the trigger var but we don't have it (field data)
-      // TODO: Add docs and link to docs on how to add the trigger var
-      if ( field.trigger === undefined ) { await scope.addToReport(scope, { type: `warning`, value: `A field on this page uses an index variable or a generic object, but the page does not contain an element with the trigger variable's name. Tell the developer to add an element to the page with the id "trigger"` }); }
+    // Make sure the trigger var matches for a page that uses proxies. Only
+    // story tables need this disambiguation.
+    if ( trigger_might_be_needed && uses_proxies && matches.length > 0 ) {
+
+      if ( !field.trigger ) {
```
Comment (rpigneri-vol) [inline lib/scope.js:928]: We have decided to change "field.trigger" to "field.triggerName" for clarity.

File: lib/scope.js [hunk 4]
```diff
@@ -909,36 +921,73 @@ module.exports = {
...
       let original_matches = matches;
+      let fallbacks = [];
       matches = [];
       for ( let match of original_matches ) {
-        // Feedback for devs - we need the trigger var but we don't have it (var data)
-        if ( match.trigger === undefined ) { await scope.addToReport(scope, { type: `warning`, value: `A field on this page uses an index variable or a generic object. The test gave story data for setting the field, but that data is missing the trigger. Add a trigger variable to the story table \`trigger\` column. For now, the test may end up ignoring this field. The row's data is\n${ JSON.stringify( match.original )}.\nThe field's data is\n${ JSON.stringify( field )}` }); }
-          // TODO: Add a warning if they're both `undefined`?
-        else {
-
+        if ( !match.trigger ) {
```
Comment (rpigneri-vol) [inline lib/scope.js:942]: Same as above: we have decided to consider calling this match.triggerName.

File: lib/scope.js [hunk 5]
```diff
@@ -878,18 +885,23 @@ module.exports = {
...
             // AVOID `.test()` - it advances through a string each time you call it on the
             // string, so you can have unexpected results.
-            uses_proxies = guess.var.match( proxies_regex );  // 
+            uses_proxies = guess.var.match( proxies_regex );
+          }
+
+          if ( var_datum.trigger === `ALKiln: no trigger variable needed` ) {
+            trigger_might_be_needed = false;
           }
           continue;
```
Comment (rpigneri-vol) [inline lib/scope.js:898]: This line could be removed as it is not changing the flow of control.

File: lib/scope.js [hunk 6]
```diff
@@ -909,36 +921,73 @@ module.exports = {
...
+          // not needed, but I'm not sure how we figure out all those things here and log
+          // a useful message.
+          let row_trigger_warning = `This story table row needs the "trigger" `
+            + `value, but it's missing. The test might get unexpected results. See `
+            + `https://suffolklitlab.org/docassemble-AssemblyLine-documentation`
+            + `/docs/automated_integrated_testing/#trigger.`
+            + `\nThe row's data is\n${ JSON.stringify( match.original )}.`
+            + `\nThis field's data is\n${ JSON.stringify( field )}`;
+          await scope.addToReport(scope, { type: `warning`, value: row_trigger_warning });
+          fallbacks.push( match );
```
Comment (rpigneri-vol) [inline lib/scope.js:954]: Collecting fallbacks, but not yet using.

We might be able to provide the developer with the variable names and values that we are setting them to.

File: lib/scope.js [hunk 7]
```diff
@@ -909,36 +921,73 @@ module.exports = {
...
-    // we now use the trigger var to narrow down the matches.
-    if ( uses_proxies && matches.length > 1 ) {
-      // Multiple matches means this came from a story
-
-      // Feedback for devs - we need the trigger var but we don't have it (field data)
-      // TODO: Add docs and link to docs on how to add the trigger var
-      if ( field.trigger === undefined ) { await scope.addToReport(scope, { type: `warning`, value: `A field on this page uses an index variable or a generic object, but the page does not contain an element with the trigger variable's name. Tell the developer to add an element to the page with the id "trigger"` }); }
+    // Make sure the trigger var matches for a page that uses proxies. Only
+    // story tables need this disambiguation.
+    if ( trigger_might_be_needed && uses_proxies && matches.length > 0 ) {
```
Comment (rpigneri-vol) [inline lib/scope.js:926]: We are thinking that it might be easier to rename "matches" to "initial_matches" to avoid changing the meaning of the matches variable halfway through.

File: lib/scope.js [hunk 8]
```diff
@@ -909,36 +921,73 @@ module.exports = {
...
         }
+      }  // ends for each match
+
+      // Be very permissive, based on feedback. See #464 comment.
+      // Use undefined trigger row(s) if no matching triggers were found
+      if ( matches.length === 0 ) { matches = fallbacks; }
+
+      // Feedback for devs on multiple row match without any matching triggers
+      if ( original_matches.length > 1 && matches.length === 0 ) {
+        let missing_row_warning = `The story table has multiple rows `
```
Comment (rpigneri-vol) [inline lib/scope.js:969]: We have decided to put "Is the story table missing a row?" as the first sentence.

File: lib/scope.js [hunk 9]
```diff
@@ -909,36 +921,73 @@ module.exports = {
...
-      // Feedback for devs - we are missing the matching triggers we need
-      if ( matches.length === 0 ) { await scope.addToReport(scope, { type: `warning`, value: `A field on this page uses an index variable or a generic object. The test gave multiple matches for the story data for the field, but none match the trigger variable. Is the story table missing a row? For now, the test will have to ignore this field. The rows' data is\n${ JSON.stringify( original_matches )}.\nThe field's data is\n${ JSON.stringify( field )}` }); }
-    }
+    }  // ends if need trigger var
 
-    // Dev may have accidentally included a row more than once. Give them feedback
+    // Dev may have accidentally included a row more than once.
     if ( matches.length > 1 ) {
-      await scope.addToReport(scope, { type: `warning`, value: `there are multiple story data matches for this field. The story table data that appears last will be used. The field's data is\n${JSON.stringify( field )}` });
+      let multiple_matches_msg = `Multiple story table rows match this field's `
```
Comment (rpigneri-vol) [inline lib/scope.js:984]: We have decided to add "Do you have a duplicate story table row?" to the front of this error message.

**Review by rpigneri-vol — APPROVED** [review]
I need additional DA context, but there is nothing too obvious here that is a cause for concern.

File: lib/scope.js (hunk 4 above)
Comment (plocket) [reply lib/scope.js:942]: This may become a future issue to do properly because it goes deep. We may be able to do something more superficial in here, though.

File: lib/scope.js (hunk 6 above)
Comment (plocket) [reply lib/scope.js:954]: Actually, I forgot the values given to the field will be visible in the info of the report later. Also, I think I misread the code. `\nThe row's data is\n${ JSON.stringify( match.original )}.` shows the data of that particular field. Resolving this for now, but let me know if we meant something different.

File: lib/scope.js [hunk 10]
```diff
@@ -65,6 +65,10 @@ module.exports = {
     let var_str = await scope.toTrimmedJSON( scope, { str: original.var });
     let value_str = await scope.toTrimmedJSON( scope, { str: original.value });
     let trigger_str = await scope.toTrimmedJSON( scope, { str: original.trigger });
+    if ( trigger_str === `ALKiln: no trigger variable needed` ) {
```
Comment (BryceStevenWilley) [inline lib/scope.js]: Suggestion: make this string a private variable elsewhere in the module. Right now, it's the same magic string being checked against multiple times, which makes it difficult if the string is changed in one place but not the other.

File: lib/scope.js [hunk 11]
```diff
@@ -818,9 +822,14 @@ module.exports = {
 
   // TODO: Maybe add `from_story_table` to the var data table (array...)
   getMatchingRows: async function ( scope, { field, var_data }) {
+
+    `PLEASE READ THE COMMENTS IN THIS FUNCTION. It's complicated.`;
+
```
Comment (BryceStevenWilley) [inline lib/scope.js]: In my opinion, I'd remove this.

File: lib/scope.js [hunk 12]
```diff
@@ -833,116 +842,183 @@ module.exports = {
...
-            // x, i, j, etc. See notes below about the reasoning
-            // AVOID `.test()` - it advances through a string each time you call it on the
-            // string, so you can have unexpected results.
-            uses_proxies = guess.var.match( proxies_regex );  // 
+        if ( this_row_matches_this_field ) {
+          rows_that_match_field_names.push( table_row );
+          // Check this until the value is set to `true` (if it ever is)
+          if ( !uses_proxies ) {
+            // If the field uses proxy variables - x, i, j, etc, flag it. See "proxies" note.
+            // AVOID `.test()` - check the MDN. You can have unexpected results.
```
Comment (BryceStevenWilley) [inline lib/scope.js]:
```suggestion
```
Just remove this comment, shouldn't need to justify use of the standard library.

File: lib/scope.js [hunk 13]
```diff
@@ -833,116 +842,183 @@ module.exports = {
...
           if ( triggers_match ) {
-            matches.push( match );
+            rows_that_also_match_trigger_name.push( a_row_that_matches_this_field );
+          } else {
+            rows_with_conflicting_trigger_names.push( a_row_that_matches_this_field );
           }
         }
+      }  // ends for each a_row_that_matches_this_field
+
+      // Be very permissive, based on feedback. See #464 comment.
```
Comment (BryceStevenWilley) [inline lib/scope.js]:
```suggestion
      // Be very permissive, based on feedback. See https://github.com/SuffolkLITLab/ALKiln/issues/464#issuecomment-1005166616
```

**Comment by BryceStevenWilley** [comment]
I'll take a closer look at scope.js and the larger changes there soon!

File: lib/scope.js [hunk 14]
```diff
@@ -841,116 +850,182 @@ module.exports = {
...
-            // AVOID `.test()` - it advances through a string each time you call it on the
-            // string, so you can have unexpected results.
-            uses_proxies = guess.var.match( proxies_regex );  // 
+        if ( this_row_matches_this_field ) {
+          rows_that_match_field_names.push( table_row );
+          // Check this until the value is set to `true` (if it ever is)
+          if ( !uses_proxies ) {
+            // If the field uses proxy variables - x, i, j, etc, flag it. See "proxies" note.
+            uses_proxies = guess.var.match( proxies_regex );
           }
```
Comment (BryceStevenWilley) [inline lib/scope.js]: Making this a one liner is a bit more clear; the if makes it seem like something depends on the initial value (which is always false). 
```suggestion
          // If the field uses proxy variables - x, i, j, etc, flag it. See "proxies" note.
          uses_proxies = uses_proxies || guess.var.match( proxies_regex );
```

File: lib/scope.js [hunk 15]
```diff
@@ -841,116 +850,182 @@ module.exports = {
...
-          continue;
-        }
+
+          let table_row_trigger_name = table_row.trigger;
+          if ( table_row_trigger_name === `ALKiln: no trigger variable needed` ) {
```
Comment (BryceStevenWilley) [inline lib/scope.js]: IMO no need to define a variable with a longer name than the original variable that's only used once.
```suggestion
          if ( table_row.trigger === `ALKiln: no trigger variable needed` ) {
```

File: lib/scope.js [hunk 16]
```diff
@@ -841,116 +850,182 @@ module.exports = {
...
+      // field/page trigger name is needed but is missing.
+      if ( !page_trigger_name ) {
+        let page_trigger_warning = `A field on this page uses an index `
+          + `variable or a generic object, but the page does not `
+          + `contain the trigger variable's name in its HTML. See `
+          + `https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing/#a-missing-trigger-variable.`;
+        await scope.addToReport(scope, { type: `warning`, value: page_trigger_warning });
+      }
+
+      for ( let a_row_that_matches_this_field of rows_that_match_field_names ) {
```
Comment (BryceStevenWilley) [inline lib/scope.js]:
```suggestion
      for ( let row_that_matches_this_field of rows_that_match_field_names ) {
```
and elsewhere

File: lib/scope.js [hunk 17]
```diff
@@ -841,116 +850,182 @@ module.exports = {
...
     * @param <field[n].guesses[n].trigger> {str} - var name that triggered this page
     * 
     * @returns [ var_data[n] ]
     */
-    let matches = [];
-    let uses_proxies = false;
 
-    // There are mutliple guesses because field names are encoded
+    let rows_that_match_field_names = [];
+    let final_matching_rows = [];
```
Comment (BryceStevenWilley) [inline lib/scope.js]: This var isn't used for about 100 lines, I'd move it closer to the relevant code.

**Review by BryceStevenWilley — APPROVED** [review]
LGTM, some optional comments that I found going through it more slowly.

File: lib/scope.js (hunk 15 above)
Comment (plocket) [reply lib/scope.js]: This was actually part of an effort I forgot about as I was going - an intermediate step for improving `.trigger` to `.trigger_name`.

Comment (plocket) [reply lib/scope.js]: Maybe I should save it for a future, more extensive, PR.

File: lib/scope.js (hunk 17 above)
Comment (plocket) [reply lib/scope.js]: I'll move it as far down as I can, though it has to be kept in the outermost scope. In js, you have to define things outside of `if` statements or they later aren't defined in the scope outside of the `if` brackets. [Which you may already know, just figured I'd include that in case it was useful.]

File: lib/steps.js [hunk 18]
```diff
@@ -66,6 +66,8 @@ let click_with = {
   pc: 'click',
 };
 
+scope.row_needs_trigger_flag = `ALKiln: no trigger variable needed`;
```
Comment (BryceStevenWilley) [inline lib/steps.js]: We may have mentioned this before, but what's the reason that this string isn't just defined inside `scope.js`? You still have the problem on needing to define it in each file that uses scope (steps and the unit test).

Comment (plocket) [reply lib/steps.js]: It was partly because I thought it was being used in steps.js (which it wasn't) and partly because I was instantiating it in the script where other state variables were being defined. I haven't defined any `scope` props in scope.js other than functions, but I can switch it to there.

Comment (plocket) [reply lib/steps.js]: Thanks for the second eye!
