### PR TITLE
#158 refactor (needs publishing) Handle proxy vars, fix signatures

### LINKED ISSUE #158: Refactor: get all fields on the page then compare to story table
Edit 2 (03/23):
Turning this into a reworking of the framework. This need was highlighted by the trouble calculating variable names of proxy variables (x, i, etc).

Changes ~for v2~:
- [x] Story table will have three columns that are basically `| var name | value | checked |`. We need another word for `checked`. This will make it much easier for developers to know what to put in each column. It will also make it more straightforward to check against those values. Not completely sure this part will work out.
- [x]  Support previous format of story table. Still not sure what 'checked' should be.

Refactors ~for v2~:
- [x] First use the string of the html to collect the data about the page (sought var, field selectors, field values), then check _that_ against the table, setting values appropriately.
- [x] Use sought var to figure out actual var names and values for proxy vars (x, i, j...).
- ~Clean up `scope.js`. Are there outdated functions in there? Do we need to split it into multiple files?~ This is holding up this issue and really belongs in its own issue.

Testing changes ~for v2~:
- [x] Add unit tests based on data, like html strings. Simpler to maintain. Less conflict with different tests trying to use the same project name (though the fix for that is in an issue already).

---
Edit 1:
We may have to do a big refactor to account for this newly discovered situation. That may include getting rid of one column in the table. Which of the three columns in the table need what information is pretty confusing as it is anyway.

---
https://docassemble.org/docs/fields.html#index%20variables. Also relevant to generic objects: https://docassemble.org/docs/modifiers.html#generic%20object.

This poses a particular problem. DOM uses literally 'i', not var name. This is fine as long as the answers are as interchangeable as this implies. If the specific variables' answers matter later on, it's more of a problem. It also poses a problem for testing generated PDFs because the order in which the vars might be set is not controlled, so you have the potential of coming out with a different PDF just because of a small change. It wouldn't even make a difference if we sort the rows alphabetically or something. If the developer changes the name of the variable, it will get out of whack. What is the solution here?

A simple example: `your_past_benefits['State Veterans Benefits']`. Here we can just replace what's inside the brackets with an 'i'. If something gets more complicated (e.g. `thing[i]['bar']`), or `thing['bar'][i]` or `thing[i][j]` do we create all combos?

Trying to discuss this upstream.

### PR DESCRIPTION
**Pull request by plocket**
#158, I think. This should [almost] finish out the refactor to collect all fields and _then_ match to the story table, adding tests for a lot of functionality.

This particular commit adds handling proxy vars. It also handles signatures, which were missed in previous commits. I would have done them separately, but I'd added them to the testing interview already, having planned to implement tests for signatures before proxy vars (and then apparently didn't). https://github.com/plocket/docassemble-cucumber/runs/2264474918?check_suite_focus=true.

This is not yet published on npm.

Edit:
Not sure if it's more helpful or harmful, but this is based on code mocked up here considering how the code had to be adjusted to work in this repo: https://replit.com/@plocket/index-vars#index.js

Edit:
I'm not sure this handles 'None of the above' yet.

### CODE REVIEW

File: lib/scope.js [hunk 1]
```diff
@@ -698,14 +758,19 @@ module.exports = {
...
     // or less than one match, this code will fail later.
     if ( matching_nodes.length === 1 ) { return selector; }
-    // Use `expect` instead. Maybe add link to issues page.
-    else { throw `${ matching_nodes.length } nodes match the '${ selector }' selector. Talk to the developers.`; }
+    // TODO: Use `expect` instead? Maybe add link to issues page. [which issue?]
+    // Submit buttons are a dime a dozen on da pages and aren't used to match variables.
+    // Everything else should be unique.
+    else if ( selector !== '#daquestion button' ) {
+      throw `${ matching_nodes.length } nodes match the '${ selector }' selector. Talk to the developers.`;
+    }
```
Comment (plocket) [inline lib/scope.js:773]: Signature fixes.

File: lib/scope.js [hunk 2]
```diff
@@ -1035,6 +1219,8 @@ module.exports = {
       await scope.afterStep(scope, { waitForShowIf: true });
     },
     CANVAS: async function ( scope, { handle, set_to }) {
+      // `<canvas>` takes a while to load
+      await scope.page.waitForSelector('#dasigcanvas');
```
Comment (plocket) [inline lib/scope.js:1223]: Signature stuff.

Comment (plocket) [reply lib/scope.js:1223]: Waits here too because of the possibility that this may be called from elsewhere.

File: lib/scope.js [hunk 3]
```diff
@@ -1133,13 +1319,20 @@ module.exports = {
...
     let fields_to_set = [];
     for ( let row of matches ) {
       let field = row.field;
 
+      // Only wait for `<canvas>`. It takes a while to load, but will never be
+      // hidden. Other elements could be hidden, though, and will never show up.
+      if ( field.tag === 'canvas' ) {
+        await scope.page.waitForSelector('#dasigcanvas');
+      }
+
```
Comment (plocket) [inline lib/scope.js:1335]: Signature stuff. What we're doing here is getting the handle to send to `.setVariable()`. To get the handle for the canvas, we have to wait. I'm debating putting this in `.setVariable()` instead. If we want to start removing puppeteer from this function, that might help. We haven't yet assessed whether that's possible or not, though.

Comment (plocket) [reply lib/scope.js:1335]: It just occurred to me this may affect other things that use `.setVariable()`. Shoot. Not enough bandwidth for this...

File: tests/features/generated_story_tables.feature [hunk 4]
```diff
@@ -90,3 +96,4 @@ Scenario: Format of story table is v1
     | textarea | | Multiline text\narea value |
     | show_3 | True | true |
     | show_2 | True | true |
+    |  |  | /sign |
```
Comment (plocket) [inline tests/features/generated_story_tables.feature:99]: I guess this should technically have two signatures. The table rows no longer get removed, though, so it's not technically necessary. If people were still going to use old tables, this may or may not be considered a problem. Have to work on the generator to see how it needs to be updated.

File: lib/scope.js (hunk 3 above)
Comment (plocket) [reply lib/scope.js:1335]: I can't find anything else using `.setVariable()`, so we should be safe.

File: lib/scope.js [hunk 5]
```diff
@@ -593,32 +595,42 @@ module.exports = {
...
       // Decsion: Do not abstract the below. There's too much data to pass around for it to make sense
-
       let $node = $( node );
-      let field_data = { selector: '', tag: node.name, rows: [], type: '' };
+      let field_data = {
+        node: node,
+        selector: '',
+        values: [],
+        var_names: [],
+        name_patterns: [],
```
Comment (niharikasingh) [inline lib/scope.js:616]: Might be useful to document somewhere what these three values mean. The `field_data` structure seems pretty important for our testing framework, so it would be good to have documentation about what it should contain.

File: lib/scope.js [hunk 6]
```diff
@@ -668,19 +681,66 @@ module.exports = {
...
+        // Get the data that will help us construct the intrinsic name later and
+        // look for the sought_var match now.
+        let pattern = await scope.getSoughtVarPatterns( scope, { field_name: name, });
+        field_data.name_patterns.push( pattern );
+        // Try to pull out the intrinsic name parts
+        let maybe_map = await scope.getProxiesToNamesMap( scope, {
+          sought_var: page_data.sought_var, pattern_data: pattern,
+        });
+        // If that works, it's the right map for the proxy values
+        if ( maybe_map ) { proxies_to_names_map = maybe_map; }
```
Comment (niharikasingh) [inline lib/scope.js:705]: I don't understand the advantage of using `maybe_map` here instead of just assigning directly to `proxies_to_names_map`

File: lib/scope.js [hunk 7]
```diff
@@ -883,6 +992,83 @@ module.exports = {
...
+          rebuilt.push( betweens[ indx/2 ] );
+        } else {
+          rebuilt.push( pattern_data.proxies[ Math.floor( indx/2 ) ]);
+        }
+      }  // end for rebuilding
+      pattern_data.name_parts = rebuilt;
+    }  // ends if has proxy parts (x, i, j, etc.)
+
+    return pattern_data;
+  },  // Ends scope.getSoughtVarPatterns()
```
Comment (niharikasingh) [inline lib/scope.js:1046]: Are we planning (hypothetically, at some point in the future) to write unit tests for the different functions in this file? This seems like a prime candidate for a lot of unit testing.

File: lib/scope.js (hunk 5 above)
Comment (plocket) [reply lib/scope.js:616]: #194!

File: lib/scope.js (hunk 6 above)
Comment (plocket) [reply lib/scope.js:705]: Good question! #196! Though having trouble of thinking of a succinct way to document it.

File: lib/scope.js (hunk 7 above)
Comment (plocket) [reply lib/scope.js:1046]: That question has been on my mind a lot too. I made #197 for it.
