### PR TITLE
#313, #314, Insert exception error messages into the reports as well

### LINKED ISSUE #313: Report: Add current `expect` messages to our custom report as well. Also just plain console logs if they're left.
Instead of just showing up with the cucumber log, they should also be in our reports. I think we may want to do both, though.

### LINKED ISSUE #314: Add auto-prefixes to some report items
[The `warning` and `error` types. Doing it now with `page_id`s.]

Hmm... should this print something like `${ item.type.toUpperCase() }: ${ item.value }\n`?

That way, we don't have to type ```{ type: `warning`, value: `WARNING: You are missing...``` every time we want to specify this is a warning etc.

_Originally posted by @niharikasingh in https://github.com/plocket/docassemble-cucumber/pull/310#discussion_r664990931_

### PR DESCRIPTION
**Pull request by plocket**
Close #313, add exception messages to reports.
Close #314, add auto-prefixes to some types of report lines.

Also adds some newlines/formatting to some messages to make those bits a bit shorter and more distinct.

### CODE REVIEW

File: lib/steps.js [hunk 1]
```diff
@@ -419,30 +443,44 @@ Then('I arrive at the next page', async () => {  // √
...
+  if ( !link ) { await scope.addToReport(scope, { type: `error`, value: msg }); }
+  expect( link, msg ).to.exist;
+
   await scope.afterStep(scope);
 });
 
-Then('I should see the link {string}', async (linkText) => {  // √
-  let [link] = await scope.page.$x(`//a[contains(text(), "${linkText}")]`);
-  expect(link).to.exist;
+Then('I should see the link to {string}', async ( url ) => {  // √
```
Comment (niharikasingh) [inline lib/steps.js:464]: The difference between "see the link xyz" and "see the link to xyz" being loosely match vs exact match isn't immediately obvious to me. Is there a way to reword this? Alternatively, you could deprecate the above function and keep just "see the link xyz". Or, you could merge the two functions somehow (first check for exact match, then if that doesn't exist, for loose match).

**Review by niharikasingh — APPROVED** [review]

File: lib/steps.js (hunk 1 above)
Comment (plocket) [reply lib/steps.js:464]: It's actually even weirder than that and I'm planning to get rid of the previous one. That one uses the visible text of the link and is not language agnostic. This one uses the href of the link and _is_ language agnostic. The concern I currently have is over links with dynamic values. It's the same concern as the one about the download links and how to handle those (#340)
