### PR TITLE
Close #572, ensure unique folder names and fail on errors and...

### LINKED ISSUE #572: Random input Step MVP: Get through a simple form by generating random input
MVP:
- [x] input field
- [x] textarea
- [x] checkbox
- [x] radio button
- [x] continue button

Stretch:
- [x] date field
- [x] number field
- [x] Custom birthdate
- [x] Custom three-part-date

Others?

Edit:

(#591)

Left to do for MVP:
- [x] Give each screenshots folder a time-stamped name in case the dev gets clever and use the same Scenario to run multiple randomized tests.
- [x] Make sure we can fail on actual errors - situations where there's a complete page or server error. Includes making an interview to test that is missing a variable definition or something.

### PR DESCRIPTION
**Pull request by plocket**
- Change some path names
- Fix failure when signature page is the first screen.
- Internal tests failing with expected failure status.
- Double printing failure in report.
- Printing failure when scenario didn't really fail. E.g.
    undefined, though need to add line in report for that.

Closes #572 for random input MVP

### CODE REVIEW

File: lib/steps.js [hunk 1]
```diff
@@ -641,7 +641,7 @@ Then(/the "([^"]+)" link opens in (a new window|the same window)/, async (linkTe
   let [link] = await scope.page.$x(`//a[contains(text(), "${linkText}")]`);
 
   let prop_obj = await link.getProperty('target');
-  let target = await await prop_obj.jsonValue();
+  let target = await prop_obj.jsonValue();
```
Comment (BryceStevenWilley) [inline lib/steps.js:644]: FYI I looked into it, and program logic wise, an extra `await` doesn't break anything. However it will wrap the value in a promise, which slows the program down a little bit more than necessary.

File: lib/steps.js [hunk 2]
```diff
@@ -793,8 +793,13 @@ When(/I answer randomly for at most ([0-9]+) (?:page(?:s)?|screen(?:s)?)/, { tim
   // Give each screenshots folder a time-stamped name in case the dev gets clever
   // and use the same Scenario to run multiple randomized tests.
   let timestamp = files.readable_date();
-  scope.paths.random_screenshots = `${ scope.paths.scenario }/random_answers_screenshots-${ timestamp }`;
+  let random_input_path = `${ scope.paths.scenario }/random_answers_screenshots-${ timestamp }`
+  scope.paths.random_screenshots = random_input_path;
   fs.mkdirSync( scope.paths.random_screenshots );
+  await scope.addToReport( scope, {
+    type: 'row',
+    value: 'Testing interview with random input'
```
Comment (BryceStevenWilley) [inline lib/steps.js]:
```suggestion
    value: `Testing interview with random input (in ${ random_input_path })`
```
just seems useful if someone wants to know where in the random tests you are

File: CHANGELOG.md [hunk 3]
```diff
@@ -38,11 +38,19 @@ Format:
...
 - 
 -->
-<!-- ## [Unreleased] -->
+## [Unreleased]
+### Changed
+- Ensure unique folder names for random input screenshots in case developer uses multiple random steps in one Scenario.
+- Ensure random input detects unexpected interview errors.
+
+### Fixed
+- Fix failure when signature page is the first screen.
```
Comment (BryceStevenWilley) [inline CHANGELOG.md:47]:
```suggestion
- Fix failure when signature page comes right before an error screen.
```

File: CHANGELOG.md [hunk 4]
```diff
@@ -38,11 +38,19 @@ Format:
...
+- Internal tests failing even when failure status is as expected.
+- Double printing in report of scenario failure, one of them even when Scenario was possibly non-failure, like skipped.
 
 ## [4.7.0] - 2022-07-27
 ### Added
-- Generate random input to fill out a simple form automatically
+- Generate random input to fill out a simple form automatically. Missing ensure unique random screenshot folder names. Missing ensure error screens are detected as errors.
```
Comment (BryceStevenWilley) [inline CHANGELOG.md]:
```suggestion
- Generate random input to fill out a simple form automatically. Does not yet ensure that random screenshot folder names are unique, or that error screens are detected as errors.
```
Also can't add it now, but it'd be nice to mention the first version that they are added in.

**Review by BryceStevenWilley — APPROVED** [review]

File: CHANGELOG.md (hunk 3 above)
Comment (plocket) [reply CHANGELOG.md:47]: Actually, the test itself failed when the signature page was the first page. `scope.getLoadData()` didn't properly recognize a signature page as a successful load.

https://github.com/SuffolkLITLab/ALKiln/pull/591/files#diff-4b632aedc4c91285de358dd7cbcc91a52724745c5c759b81b3a6d80e8d6d7abcR622

File: CHANGELOG.md (hunk 4 above)
Comment (plocket) [reply CHANGELOG.md]: Good update. Not completely convinced the version name is required since the changelog will show when those get added, but it won't do harm. I'll try to remember when I bump the version.
